import Head from "next/head";

// components
import { PostCard, PostWidget, Categories } from "../components";

// import posts from graphql services
import { getPosts } from "@/services";

export default function Home({ posts }) {
  return (
    <div className="container mx-auto px-10 mb-8 text-gray-700">
      <Head>
        <title>Stojanovska Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Grid container */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        {/* Posts container */}
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post, i) => (
            <PostCard post={post.node} key={post.title} />
          ))}
        </div>

        {/* Second container */}
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <PostWidget />
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui
              dolor, hic, debitis at et voluptatum sapiente, quae pariatur nihil
              consectetur quod molestias dolorum explicabo ad dolore ea error
              cum aut corrupti maxime rem harum quis excepturi fugiat? Nobis,
              nisi! Odio.
            </p>
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
}

// posts fetching
export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: { posts },
  };
}
